#!/usr/bin/env node

/**
 * DevContext Memory Bank Generator
 * Generates memory bank files from templates and configuration
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { TemplateEngine } from './template-engine.js';
import { BriefGenerator } from './content-generators/brief.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load configuration
const configPath = process.env.EMBEDCONTEXT_CONFIG || path.join(process.cwd(), 'embedcontext.json');

let config;
try {
  const configContent = readFileSync(configPath, 'utf-8');
  config = JSON.parse(configContent);
} catch (error) {
  console.error('Error loading configuration from:', configPath);
  console.error('Make sure embedcontext.json exists or set EMBEDCONTEXT_CONFIG environment variable');
  process.exit(1);
}

// Paths
const MEMORY_BANK_DIR = path.join(config.rootDir, '.claude', 'memory-bank');
const TEMPLATES_DIR = path.join(__dirname, '../templates');

/**
 * Main generation function
 */
async function generateMemoryBank() {
  console.log(`\n🔄 Generating memory bank for ${config.projectName}...\n`);

  // Ensure directories exist
  mkdirSync(path.join(MEMORY_BANK_DIR, 'core'), { recursive: true });
  mkdirSync(path.join(MEMORY_BANK_DIR, 'knowledge'), { recursive: true });

  try {
    // Generate brief
    console.log('📝 Generating brief.md...');
    const briefGen = new BriefGenerator(config);
    const briefData = await briefGen.generate();
    const briefContent = TemplateEngine.renderLoop(
      path.join(TEMPLATES_DIR, 'core/brief.md.template'),
      briefData,
      'domains',
      briefData.domains
    );
    writeFileSync(path.join(MEMORY_BANK_DIR, 'core/brief.md'), briefContent);

    // Generate context
    console.log('📝 Generating context.md...');
    const contextData = {
      projectName: config.projectName,
      projectType: config.projectType,
      rootDir: config.rootDir,
      embeddingsModel: config.embeddingsModel || 'nomic-embed-text',
      domainCount: config.domains.length,
      totalChunks: 'Unknown (run indexing first)',
      lastUpdated: new Date().toISOString().split('T')[0]
    };
    const contextContent = TemplateEngine.render(
      path.join(TEMPLATES_DIR, 'core/context.md.template'),
      contextData
    );
    writeFileSync(path.join(MEMORY_BANK_DIR, 'core/context.md'), contextContent);

    // Generate placeholder files for other core documents
    const placeholders = [
      {
        file: 'product.md',
        content: `# ${config.projectName} - Product Overview\n\n*Auto-generated placeholder. Customize this file with your product details.*\n\n## Features\n\nDescribe your key features here.\n`
      },
      {
        file: 'architecture.md',
        content: `# ${config.projectName} - Architecture\n\n*Auto-generated placeholder. Customize this file with your architecture details.*\n\n## System Design\n\nDescribe your system architecture here.\n`
      },
      {
        file: 'tech.md',
        content: `# ${config.projectName} - Technology Stack\n\n*Auto-generated placeholder. Customize this file with your tech stack.*\n\n## Technologies\n\nProject Type: ${config.projectType}\n\nList your key technologies and frameworks here.\n`
      }
    ];

    for (const placeholder of placeholders) {
      const filePath = path.join(MEMORY_BANK_DIR, 'core', placeholder.file);
      if (!existsSync(filePath)) {
        console.log(`📝 Creating ${placeholder.file}...`);
        writeFileSync(filePath, placeholder.content);
      } else {
        console.log(`⏭️  Skipping ${placeholder.file} (already exists)`);
      }
    }

    // Generate domain knowledge files
    console.log('\\n📚 Generating domain knowledge files...');
    for (const domain of config.domains) {
      const knowledgeContent = `# ${domain.name} - Domain Knowledge\n\n*Last Updated: ${new Date().toISOString().split('T')[0]}*\n\n## Overview\n\n${domain.description}\n\n## File Patterns\n\n${domain.patterns.map(p => `- \`${p}\``).join('\\n')}\n\n## Key Components\n\n*Add your domain-specific knowledge here. This file will be used by Claude Code to understand the ${domain.name} domain.*\n\n---\n*Auto-generated by DevContext*\n`;

      const filePath = path.join(MEMORY_BANK_DIR, 'knowledge', `${domain.name}.md`);
      console.log(`  📝 ${domain.name}.md`);
      writeFileSync(filePath, knowledgeContent);
    }

    console.log(`\n✅ Memory bank generated successfully!\n`);
    console.log(`📁 Location: ${MEMORY_BANK_DIR}\n`);
    console.log(`Files created:`);
    console.log(`  - core/brief.md`);
    console.log(`  - core/context.md`);
    console.log(`  - core/product.md (placeholder)`);
    console.log(`  - core/architecture.md (placeholder)`);
    console.log(`  - core/tech.md (placeholder)`);
    config.domains.forEach(d => console.log(`  - knowledge/${d.name}.md`));
    console.log();

  } catch (error) {
    console.error('\\n❌ Error generating memory bank:', error);
    process.exit(1);
  }
}

// Run generation
generateMemoryBank().catch(console.error);
